### ISSUE TITLE
Custom Invo Sync Failed!

### ISSUE THREAD

**Issue by MyasisDragon** [Funwayguy/InfiniteInvo#33]
I'm getting a lot of these in the log files. 

[07:24:51] [Server thread/ERROR] [infiniteinvo]: Custom Invo Sync Failed! Server
 hasn't opened the matching container yet...

I can reproduce it on demand by opening the smeltery contoller (rt-click) in Tinker Construct.

**Comment by Govorunb** [comment]
Having the same issue here, my client crashes every time it happens. Playing the FTB Infinity pack.
Here's a bunch of console entries leading up to the crash, the crash log itself shows the same error:

[15:00:29] [Server thread/ERROR] [infiniteinvo]: Custom Invo Sync Failed! Server hasn't opened the matching container yet...
[15:00:29] [Client thread/INFO] [inventorytweaks]: jotato.quantumflux.gui.GuiQuibitCluster
[15:00:29] [Client thread/INFO] [inventorytweaks]: jotato.quantumflux.inventory.ContainerQuibitCluster
[15:00:30] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$InitGuiEvent$Post@798b9780:
java.lang.ClassCastException: net.minecraft.client.entity.EntityClientPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at jotato.quantumflux.inventory.ContainerQuibitCluster.func_75142_b(ContainerQuibitCluster.java:33) ~[ContainerQuibitCluster.class:?]
	at infiniteinvo.client.inventory.InvoScrollBar.InitDefault(InvoScrollBar.java:116) ~[InvoScrollBar.class:?]
	at infiniteinvo.client.inventory.InvoScrollBar.<init>(InvoScrollBar.java:57) ~[InvoScrollBar.class:?]
	at infiniteinvo.handlers.EventHandler.onGuiPostInit(EventHandler.java:266) ~[EventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_383_EventHandler_onGuiPostInit_Post.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:257) [bdw.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:797) [bao.class:?]
	at cpw.mods.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:445) [FMLClientHandler.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:303) [FMLCommonHandler.class:?]
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:94) [FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209) [yz.class:?]
	at jotato.quantumflux.blocks.BlockQuibitCluster.func_149727_a(BlockQuibitCluster.java:32) [BlockQuibitCluster.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326) [bje.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[15:00:30] [Client thread/ERROR] [FML]: Index: 2 Listeners:
[15:00:30] [Client thread/ERROR] [FML]: 0: NORMAL
[15:00:30] [Client thread/ERROR] [FML]: 1: ASM: tconstruct.client.tabs.TabRegistry@382c46b5 guiPostInit(Lnet/minecraftforge/client/event/GuiScreenEvent$InitGuiEvent$Post;)V
[15:00:30] [Client thread/ERROR] [FML]: 2: ASM: infiniteinvo.handlers.EventHandler@12f20643 onGuiPostInit(Lnet/minecraftforge/client/event/GuiScreenEvent$InitGuiEvent$Post;)V
[15:00:30] [Client thread/ERROR] [FML]: 3: ASM: baubles.client.gui.GuiEvents@6cbc8b63 guiPostInit(Lnet/minecraftforge/client/event/GuiScreenEvent$InitGuiEvent$Post;)V
[15:00:33] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2817ms behind, skipping 56 tick(s)
[15:00:33] [Server thread/INFO]: Stopping server
[15:00:33] [Server thread/INFO]: Saving players
[15:00:33] [Server thread/INFO]: Saving worlds

**Comment by Funwayguy** [comment]
@MyasisDragon I've noticed a lot of sync errors server side on InfiniteInvo and I've been needing to take a look at it and figure out exactly why.
@Govorunb That crash is a class casting oversight in quantumflux that needs to be fixed in their container (ContainerQuibitCluster). Please report the crash to them as their isn't much I can do from my side.

**Comment by Funwayguy** [comment]
This should be fixed now. I added an extra tick to the sync delay to make sure the server side container is all setup first

**Comment by MyasisDragon** [comment]
Thank you very much my friend. I will check it out and if there are any further issues I will let ya know :D
